#!/usr/bin/env python3
import wave
import random
import struct
import sys
import math

"""
Generate a header file with an array mapping each ASCII character to the tone_switch_period
of the corresponding piano key.
"""
if len(sys.argv) < 3:
    print("Usage: ./piano_scale_generator <output header file> <cpu clock frequency>")
    print("Example: ./piano_scale_generator scale.h 50e6")
    sys.exit(1)
output_file = sys.argv[1]
clock_freq = float(sys.argv[2])
# Can supply custom clock frequency, otherwise defaults to 50 Mhz
if len(sys.argv) > 2:
    clock_freq = float(sys.argv[2])
else:
    clock_freq = 30.0e3

note_map = {
    'Z': 65.4064,
    'S': 69.2957,
    'X': 73.4162,
    'D': 77.7817,
    'C': 82.4069,
    'V': 87.3071,
    'G': 92.4986,
    'B': 97.9989,
    'H': 103.826,
    'N': 110.000,
    'J': 116.541,
    'M': 123.471,
    '<': 130.813,

    'z': 130.813,
    's': 138.591,
    'x': 146.832,
    'd': 155.563,
    'c': 164.814,
    'v': 174.614,
    'g': 184.997,
    'b': 195.998,
    'h': 207.652,
    'n': 220.000,
    'j': 233.082,
    'm': 246.942,
    ',': 261.626,

    'q': 261.626,
    '2': 277.183,
    'w': 293.665,
    '3': 311.127,
    'e': 329.628,
    'r': 349.228,
    '5': 369.994,
    't': 391.127,
    '6': 415.305,
    'y': 440.000,
    '7': 466.164,
    'u': 493.883,
    'i': 523.251,

    'Q': 523.251,
    '@': 554.365,
    'W': 587.330,
    '#': 622.254,
    'E': 659.255,
    'R': 698.456,
    '%': 739.989,
    'T': 783.991,
    '^': 830.609,
    'Y': 880.000,
    '&': 932.328,
    'U': 987.767,
    'I': 1046.50
}

note_map_2 = {
    'Z': 82.4069,
    'S': 87.3071,
    'X': 92.4986,
    'D': 97.9989,
    'C': 103.826,
    'V': 110.000,
    'G': 116.541,
    'B': 123.471,
    'H': 130.813,
    'N': 138.591,
    'J': 146.832,
    'M': 156.563,
    '<': 164.814,

    'z': 164.814,
    's': 174.614,
    'x': 184.997,
    'd': 195.998,
    'c': 207.652,
    'v': 220.000,
    'g': 233.082,
    'b': 246.942,
    'h': 261.626,
    'n': 277.183,
    'j': 293.665,
    'm': 311.127,
    ',': 329.628,

    'q': 329.628,
    '2': 349.228,
    'w': 369.994,
    '3': 391.127,
    'e': 415.305,
    'r': 440.000,
    '5': 466.164,
    't': 493.883,
    '6': 523.251,
    'y': 554.365,
    '7': 587.330,
    'u': 622.254,
    'i': 659.255,

    'Q': 659.255,
    '@': 698.456,
    'W': 739.989,
    '#': 783.991,
    'E': 830.609,
    'R': 880.000,
    '%': 932.328,
    'T': 987.767,
    '^': 1046.50,
    'Y': 1108.73,
    '&': 1174.66,
    'U': 1244.51,
    'I': 1318.51
}

note_map_3 = {
    'Z': 97.9989,
    'S': 103.826,
    'X': 110.000,
    'D': 116.541,
    'C': 123.471,
    'V': 130.813,
    'G': 138.591,
    'B': 146.832,
    'H': 155.563,
    'N': 164.814,
    'J': 174.614,
    'M': 184.997,
    '<': 195.998,
    
    'z': 195.998,
    's': 207.652,
    'x': 220.000,
    'd': 233.082,
    'c': 246.942,
    'v': 261.626,
    'g': 277.183,
    'b': 293.665,
    'h': 311.127,
    'n': 329.628,
    'j': 349.228,
    'm': 369.994,
    ',': 391.127,

    'q': 391.127,
    '2': 415.305,
    'w': 440.000,
    '3': 466.164,
    'e': 493.883,
    'r': 523.251,
    '5': 554.365,
    't': 587.330,
    '6': 622.254,
    'y': 659.255,
    '7': 698.456,
    'u': 739.989,
    'i': 783.991,

    'Q': 783.991,
    '@': 830.609,
    'W': 880.000,
    '#': 932.328,
    'E': 987.767,
    'R': 1046.50,
    '%': 1108.73,
    'T': 1174.66,
    '^': 1244.51,
    'Y': 1318.51,
    '&': 1396.91,
    'U': 1479.98,
    'I': 1567.98
}

piano_output_file = open(output_file, 'w')
piano_output_file.write('static const uint32_t switch_periods_3[256] = {\n')
for ascii_index in range(128):
    if chr(ascii_index) in note_map:
        note_freq = note_map_3[chr(ascii_index)]
        note_tone_switch_period = round(float(2 ** 24) * float(note_freq) / float(clock_freq))
        piano_output_file.write("    ['{}'] = {},\n".format(chr(ascii_index), note_tone_switch_period))
piano_output_file.write('};')
piano_output_file.close()
